### ISSUE TITLE
"Table" does not display the title

### ISSUE THREAD

**Issue by benjamineich** [Azure/ibex-dashboard#372]
Hi,
is it possible to display a title in the table view control? I've already set the title property, but it's only used in the popup.

In other controls, the title is displayed at the top of the control (e.g. "Intents Graph" in BarData).

Cheers, Benji

**Comment by morsh** [comment]
Hi @benjamineich - Currently the way we set titles for tables is using the header of the first column like here:
https://github.com/Azure/ibex-dashboard/blob/master/server/dashboards/preconfigured/bot-framework-inst.ts#L623

Where we set the header test to be `Top 5 Positive`

**Comment by benjamineich** [comment]
Hi @morsh Thank you for the fast response! I'll do it the way you suggested.
