### ISSUE TITLE
Microsoft login issue

### ISSUE THREAD

**Issue by Albert1389** [Azure/ibex-dashboard#381]
Hey,

i get an error when i want to log in via AD. Can anyone help me?
I follow the steps under the (?).

![screenshot_ad](https://user-images.githubusercontent.com/37581948/41605845-98e7d10e-73e2-11e8-87a3-e55bcc73f226.PNG)

BR

**Comment by morsh** [comment]
Hi @Albert1389 - In my experience this issue usually rises when the ID you've provided is:

- Not the appropriate field (There are two different fields: Application ID and Object ID)
- Copying the necessary field inappropriately (extra spaces / not all the numbers)

Let me know if going over those solves your problem.

**Comment by Albert1389** [comment]
Hi @morsh, ty for your reply.
The problem was that I had the wrong directory.
