### ISSUE TITLE
How can I delete a corrupt dashboard

### ISSUE THREAD

**Issue by DavidCampaneroGarcia** [Azure/ibex-dashboard#383]
Is there any way to delete a dashboard aside of go in and click manually on More/Delete Dashboard?

I made one and it freezes my screen everytime I access to it, so I can't delete it via website.

**Comment by morsh** [comment]
@DavidCampaneroGarcia - Yes there is, if you go to the file system (explorer locally, or kudu on Azure) you can simply delete the dashboard file under /server/dashboards

**Comment by DavidCampaneroGarcia** [comment]
Hey @morsh. That worked! Thank you very much for the fast answer! :)
