### ISSUE TITLE
Support for Bot Framework SDK V4

### ISSUE THREAD

**Issue by RamPrasadMeenavalli** [Azure/ibex-dashboard#388]
Does this work with Bot Framework SDK V4?
If yes, it would be helpful if someone can share the documentation on how to add the instrumentation code.
If not, is there any plan to make this dashboard working for V4?

Thank you.

**Comment by jkolonko** [comment]
@RamPrasadMeenavalli The dashboard is version-agnostic, it just needs the right events to be sent to App Insights. Have a look at this project: https://github.com/ObjectivityLtd/Bot.Ibex.Instrumentation 
It is a younger brother of https://github.com/Azure/botbuilder-instrumentation package, just rewritten for V4.

**Comment by RamPrasadMeenavalli** [comment]
> 
> 
> @RamPrasadMeenavalli The dashboard is version-agnostic, it just needs the right events to be sent to App Insights. Have a look at this project: https://github.com/ObjectivityLtd/Bot.Ibex.Instrumentation
> It is a younger brother of https://github.com/Azure/botbuilder-instrumentation package, just rewritten for V4.

Thank you @jkolonko . I will try this.

**Comment by starstuck** [comment]
Is there any nodejs package for instrumentation with botbuilder V4?

If not, I could write one, but is there some documentation what events should such integration emit, (ideally with explanation of payload)?

**Comment by starstuck** [comment]
Just for anyone that may be interested in running dashboard with botbuilder-js V4, I have prepared a PR upgrading botbuilder-instrumentaion to most recent version of framework Azure/botbuilder-instrumentation#24
