### ISSUE TITLE
Visual Plugin - Date filter (with sliding window)

### ISSUE THREAD

**Issue by morsh** [Azure/ibex-dashboard#79]
Create a new filter that allows filtering dates by sliding windows up to 3 months.

**Comment by gregdegruy** [comment]
I'll take a stab at this, looks fun Just making this pretty much right > 📅

**Comment by gregdegruy** [comment]
https://github.com/react-component/calendar < Calendar component. completing work on #63 for now. feel free to assign this to someone else.

**Comment by deadlyfingers** [comment]
We are using react-md for components. So we should use https://react-md.mlaursen.com/components/pickers/date instead.

**Comment by morsh** [comment]
Closing since this issue was resolved by @CristianPQ
